name: Shell Script CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Shell Script Analysis
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    
    - name: Run ShellCheck
      run: |
        shellcheck --version
        shellcheck -x xray-auto-install.sh
    
    - name: Check script permissions
      run: |
        if [ ! -x "xray-auto-install.sh" ]; then
          echo "Warning: Script is not executable"
          chmod +x xray-auto-install.sh
        fi
    
    - name: Validate script syntax
      run: |
        bash -n xray-auto-install.sh
        echo "Script syntax is valid"

  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security scan
      run: |
        # Check for common security issues
        echo "Checking for hardcoded credentials..."
        if grep -i "password\|secret\|key" xray-auto-install.sh | grep -v "enter\|input\|read"; then
          echo "Warning: Potential hardcoded credentials found"
          exit 1
        fi
        
        echo "Checking for dangerous commands..."
        if grep -E "rm -rf /|mkfs|dd if=" xray-auto-install.sh; then
          echo "Error: Dangerous commands found"
          exit 1
        fi
        
        echo "Security scan passed"

  test-basic-functions:
    runs-on: ubuntu-latest
    name: Test Basic Functions
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test script functions
      run: |
        chmod +x xray-auto-install.sh
        
        # Test help function
        bash xray-auto-install.sh --help || echo "Help function test completed"
        
        # Test version function
        bash xray-auto-install.sh --version || echo "Version function test completed"
        
        # Validate configuration templates
        echo "Testing configuration templates..."
        if ! grep -q "inbounds" xray-auto-install.sh; then
          echo "Error: Xray configuration template missing"
          exit 1
        fi
        
        echo "Basic function tests passed"

  documentation-check:
    runs-on: ubuntu-latest
    name: Documentation Check
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check documentation
      run: |
        # Check if README exists and has required sections
        if [ ! -f "README.md" ]; then
          echo "Error: README.md not found"
          exit 1
        fi
        
        required_sections=("Installation" "Usage" "Features" "Troubleshooting")
        for section in "${required_sections[@]}"; do
          if ! grep -q "$section" README.md; then
            echo "Warning: $section section missing in README.md"
          fi
        done
        
        # Check if CHANGELOG exists
        if [ ! -f "CHANGELOG.md" ]; then
          echo "Warning: CHANGELOG.md not found"
        fi
        
        echo "Documentation check completed"

  license-check:
    runs-on: ubuntu-latest
    name: License Check
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check license
      run: |
        if [ ! -f "LICENSE" ]; then
          echo "Warning: LICENSE file not found"
        else
          echo "License file found"
        fi
