name: Bug Report
description: Create a bug report to help us improve the Xray Auto Install Script
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        
        Before submitting, please:
        1. Search existing issues to avoid duplicates
        2. Make sure you're using the latest version
        3. Check the troubleshooting section in README.md

  - type: input
    id: version
    attributes:
      label: Script Version
      description: What version of the script are you using?
      placeholder: "2.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you running?
      options:
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Debian 10
        - Debian 11
        - Debian 12
        - CentOS 7
        - CentOS 8
        - Rocky Linux 8
        - Rocky Linux 9
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: installation_type
    attributes:
      label: Installation Type
      description: How did you install the script?
      options:
        - Fresh installation
        - Upgrade from previous version
        - Reinstallation
        - Custom installation
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: "When I try to create a new user, the script fails with..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The user should be created successfully and I should receive the configuration..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'menu' command
        2. Select option '1' to create user
        3. Enter username 'testuser'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
      placeholder: |
        [ERROR] Failed to create user: testuser
        [ERROR] Database connection failed
        ...

  - type: textarea
    id: configuration
    attributes:
      label: Configuration Details
      description: Any relevant configuration details (remove sensitive information)
      render: yaml
      placeholder: |
        Domain: example.com
        SSL: Let's Encrypt
        Protocols: VMess, VLESS, Trojan
        ...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I am using the latest version of the script
          required: true
        - label: I have checked the troubleshooting section
          required: true
        - label: I have removed any sensitive information from logs
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This started happening after I updated my domain settings..."
